application:
  title: Hackaton
  version: 1.0

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Hackaton
  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/processor_db

server:
  servlet:
    context-path: /api
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
  path: swagger-ui-custom.html

aws:
  account:
    number: 115666561529
  region:
    name: us-east-1
  sqs:
    notificator:
      queue: sqs-request-video-notificator
    processor:
      queue: sqs-request-video-processor
  s3:
    bucket:
        in:
          name: processor-in
          file:
            type: video/mp4
        out:
          name: processor-out
