apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-processor
  labels:
    app: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: 115353667788.dkr.ecr.us-east-1.amazonaws.com/fiap-mpeg-processor:1.0
          imagePullPolicy: Always
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-processor
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: cm-processor
          ports:
            - containerPort: 8080